<?php 
 	
		error_reporting(1); 
			
			if(!isset($_SESSION))session_start();
		/// authenticate the downloader

		if(!isset($_SESSION['adminUser'])) {	
			$_SESSION['adminReqPg'] = $_SERVER['PHP_SELF'];			
			header("Location:login/");	
		}
		else{
			require "../media/php/connector.php";			 
			require "../media/Classes/PHPExcel.php";
			
			$dbm = new DbTool(); 
			 
			try{  	 
			////////////////////////////////////////
			//// trap request from browser
			///////////////////////////////////////////////////////////
			  

			 $fields = array('user_id','codegen','percent','sn');
			  
			 // $queries = array("codegen"=>$code,"year"=>$year); 		  
			 // $infos = explode("-",$_SESSION['resCond']);
			 $codes = explode("_",$_SESSION['resCond']['codegen']);
			 $myear = $_SESSION['resCond']['year'];
			 $cnt = count($codes); /// date == n-1
	 		 $dates = array_slice($codes,$cnt-2,1)[0];
			 $month = substr($dates,0,2);
			 $day = substr($dates,2); 
			 
			 $Result = $dbm->getFields($dbm->select("users_result",$_SESSION['resCond'],array("user_id")),$fields);	
			  					
			////////////////////////////////////////////////////////////////////////	
			////////excel header ////////////////////////

			$headings = array('SENDER','PHONE NO','MESSAGE');	 			
			// start PHPExcel object 
				  $menuheadings = "SMS TEMPLATE FOR PAPER WRITTEN ON  : ". substr(date("r",mktime(0,0,0,$month,$day,$myear)),0,16);
						
			  $extName = $_SESSION['resCond']['codegen']."_result.xlsx";
			
			$objPhp = new PHPExcel();
			$objPhp->getProperties()->setCreator("HKKonsults")
				->setLastModifiedBy("Ojo Isaac Mayowa")
				->setTitle("Office 2007 XLSX Test Document")
				->setSubject("Office 2007 XLSX Test Document")
				->setDescription("Student General Result generated by PHPExcel.")
				->setKeywords("office 2007 openxml php")
				->setCategory("Exam Result File");
			
			
			$objPhp->getActiveSheet()->setTitle("RESULT SMS TEMPLATE");				
			$rowNo = 1; 
			$col = "B";
			 foreach($headings as $heads){
				$objPhp->getActiveSheet()->setCellValue($col.$rowNo,$heads); 
				$objPhp->getActiveSheet()->getColumnDimension($col)->setWidth(20); // auto adjust the width
				$col++;			
			}
				
				/// write the students phone and score 
				$objPhp->getActiveSheet()->getStyle('B4:D4')->getAlignment()->setWrapText(true); 
			
				$rowNo = 2; $col='D';	$f = 0;
				foreach($Result['percent'] as $score){
					
					if(is_null($score)) $score = 0;
					
					$myInfo = $dbm->resort($dbm->getFields($dbm->select("users",array("user_id"=>$Result['user_id'][$f])),array('surname','firstname','midname','phone')));	
					
					$fname = strtoupper($myInfo['surname']).", ".$myInfo['firstname']." ".$myInfo['midname'];
					
					$message = "Hi, ".$fname.", Your Over All Score  for the exam is : ".$score."%, Congrats ";
					
					$objPhp->getActiveSheet()->setCellValue($col.$rowNo,$message);
					
					$objPhp->getActiveSheet()->setCellValue('B'.$rowNo,'KWSNURSING'); 	// write the serial numbers 
					
					$objPhp->getActiveSheet()->setCellValue('C'.$rowNo,$myInfo['phone']); 	// write the serial numbers 
					
					$objPhp->getActiveSheet()->getStyle('B'.$rowNo.':D'.$rowNo)->getAlignment()->setWrapText(true); 
					
					$rowNo++; $f++;
				}
				
				/// freeze pane so that heading lines won't scroll 
				$objPhp->getActiveSheet()->freezePane('A2');
				// save an excell BIFF(XLS) file
			// $objWriter = PHPExcel_IOFactory::createWriter($objPhp,'Excel5');  // for xls file  
			$objWriter = PHPExcel_IOFactory::createWriter($objPhp,'Excel2007'); 
			// $objWriter = PHPExcel_IOFactory::createWriter($objPhp,'PDF');  // for pdf 
			header('Content-Type:application/vnd.ms-excel');
			header('Content-disposition:attachment;filename="'.$extName);
			header('Cache-Control:max-age=0');
			$objWriter->save('php://output');
			// $objWriter->save('MyExcel.xslx);
			exit();
				//
				
				
			} 		
			catch(Exception $e){
				throw  $e; 
				}
			
			}
				
			 // end of request token 
			////////////////////
			
			
			
			///////////downloading question//// 
			///////////////////////////////////
			if(isset($_REQUEST['samp'])){
			$filepath = "../scripts/files/";
			$fname = "question.xls";
				// http headers for excel downloads
				header("Pragma: public");
				header("Expires: 0");
				header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
				header("Cache-Control: public");
				header("Content-Description: File Transfer");
				header("Content-type: application/vnd.ms-excel");
				header("Content-Disposition: attachment; filename=$fname");
				header("Content-Transfer-Encoding: binary");
				header("Content-Length: ".filesize($filepath.$fname));
				ob_end_flush();
				@readfile($filepath.$fname);
			
			
			}
			// end of qtnsamp
			//////////////////////////////////////////////////////

		//end of else 

		?>