<?php 
 	
		error_reporting(1); 
			
			if(!isset($_SESSION))session_start();
		/// authenticate the downloader

		if(!isset($_SESSION['adminUser'])) {	
			$_SESSION['adminReqPg'] = $_SERVER['PHP_SELF'];			
			header("Location:login/");	
		}
		else{
			require "../media/php/connector.php";			 
			require "../media/Classes/PHPExcel.php";
			
			$dbm = new DbTool(); 
			 
			try{  	 
			////////////////////////////////////////
			//// trap request from browser
			///////////////////////////////////////////////////////////
			 /////////// query the database and fetch all fields needed
			 $fields = array('user_id','code','qtype','totalmark','totalscore','percent','paper_signal','paperlogintime','paperlogouttime');
			  
			 // $queries = array("coursecode"=>$code,"year"=>$year); 		  
			 
			 $Result = $dbm->getFields($dbm->select("users_result",$_SESSION['resCond'],array("user_id")),$fields);	
			  
					
			////////////////////////////////////////////////////////////////////////	
			////////excel header ////////////////////////

			$headings = array('MATRIC.NO.','COURSE CODE ','PAPER TYPE','EXPECTED MARK','SCORE','PERCENT','PAPER STATUS','TIME IN ', 'TIME OUT ');	 			
			// start PHPExcel object 
			  $extName = "result.xls";
			// $extName = $code.".xls";
			$objPhp = new PHPExcel();
			$objPhp->getProperties()->setCreator("HKKonsults")
				->setLastModifiedBy("Ojo Isaac Mayowa")
				->setTitle("Office 2007 XLSX Test Document")
				->setSubject("Office 2007 XLSX Test Document")
				->setDescription("Student General Result generated by PHPExcel.")
				->setKeywords("office 2007 openxml php")
				->setCategory("Test result file");
			$objPhp->getActiveSheet()->setTitle("RESULT");				
			$rowNo = 2; 
			$col = "B";
			 foreach($headings as $heads){
				$objPhp->getActiveSheet()->setCellValue($col.$rowNo,$heads); 
				$col++;			
			}
				// loop through the result 
				$rowNo = 3;
				$r = 0;
				foreach($Result['user_id'] as $studs){ 	 
				$col='B';	
				foreach($fields as $cell){
					$objPhp->getActiveSheet()->setCellValue($col.$rowNo,$Result[$cell][$r]);
					$col++;
				}
				$rowNo++;
					$r++;		 
				}
				/// freeze pane so that heading lines won't scroll 
				$objPhp->getActiveSheet()->freezePane('A2');
				// save an excell BIFF(XLS) file
			// $objWriter = PHPExcel_IOFactory::createWriter($objPhp,'Excel5');  // for xls file  
			$objWriter = PHPExcel_IOFactory::createWriter($objPhp,'Excel2007'); 
			// $objWriter = PHPExcel_IOFactory::createWriter($objPhp,'PDF');  // for pdf 
			header('Content-Type:application/vnd.ms-excel');
			header('Content-disposition:attachment;filename="'.$extName);
			header('Cache-Control:max-age=0');
			$objWriter->save('php://output');
			// $objWriter->save('MyExcel.xslx);
			exit();
				//
			} 		
			catch(Exception $e){
				throw  $e; 
				}
			
			}
				
			 // end of request token 
			////////////////////
			
			
			
			///////////downloading question//// 
			///////////////////////////////////
			if(isset($_REQUEST['samp'])){
			$filepath = "../scripts/files/";
			$fname = "question.xls";
				// http headers for excel downloads
				header("Pragma: public");
				header("Expires: 0");
				header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
				header("Cache-Control: public");
				header("Content-Description: File Transfer");
				header("Content-type: application/vnd.ms-excel");
				header("Content-Disposition: attachment; filename=$fname");
				header("Content-Transfer-Encoding: binary");
				header("Content-Length: ".filesize($filepath.$fname));
				ob_end_flush();
				@readfile($filepath.$fname);
			
			
			}
			// end of qtnsamp
			//////////////////////////////////////////////////////

		//end of else 

		?>